version = 0.1

[default.deploy.parameters]
stack_name = "serverless-user-directory"
resolve_s3 = true
s3_prefix = "serverless-user-directory"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "us-east-1"
